WAKATIME_API_KEY=de2515ab-0ce1-43dd-ac27-464db5470224
GH_TOKEN=68191f664788743cd4b384d94c14e61dcf3e1ef3

SHOW_LINES_OF_CODE=true
SHOW_OS=false
SHOW_PROJECTS=flase
SHOW_TIMEZONE=false
SHOW_LANGUAGE_PER_REPO=false


name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
